import { rupees } from '@/lib/today/time';

import type { PortalNotificationWire } from './api';

/**
 * THE CLIENT'S BELL — §"Notifications", item 8 of the spec's build order.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * THE RULE THE WHOLE SURFACE RESTS ON
 *
 * §"Notifications" states it in four words: **notifications come from the
 * trainer, not the platform.** The spec then draws the line as a table, and the
 * right-hand column is not a set of switches to leave off — it is a set of
 * messages this product does not send at all:
 *
 *   | Send | Don't send |
 *   | --- | --- |
 *   | *Arun updated your program* | *Don't forget to work out!* |
 *   | *Session tomorrow, 6:30am* | *You haven't opened the app in 3 days* |
 *   | *You beat your squat PR* | *Your streak is about to end!* |
 *   | *Arun left you a note* | Anything at all on a rest day |
 *
 * So every kind below is either a trainer's write landing on this client's book
 * or a milestone the product observed, and there is nothing else. A row cannot
 * be generated by this app having an opinion about how often somebody trains.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * AND IT IS THE SAME DISTINCTION THE TRAINER'S BELL IS BUILT ON
 *
 * `lib/notifications/types.ts` opens with it and it transfers unchanged:
 *
 *   Home's hero and pack strip   the STATE.  True until something changes it.
 *   The bell                     the RECORD. Happened once, read once, history.
 *
 * Which is why **there is no `reminder` kind**, though the spec's Send column
 * names one. *Session tomorrow, 6:30am* is a message about the future: it is
 * not something that happened, it goes stale by itself, and Home's hero already
 * says it bigger and sooner. `sessionReminder` is still a switch — it governs
 * what SMS and WhatsApp send — and in the feed it governs `session` rows, which
 * are the three things a trainer can do to a booking.
 *
 * ── A ROW CARRIES NO VERB, HERE TOO ─────────────────────────────────────────
 *
 * Nothing in this feed offers to change anything. Each row names what happened
 * and links to the screen holding the full fact — never to a detail view of the
 * notification, because there is no such screen and there should not be. A
 * pointer that leads to a copy of itself has not moved anybody forward.
 */
export type ClientNotificationKind = 'note' | 'plan' | 'session' | 'pack' | 'best';

const KINDS: ClientNotificationKind[] = ['note', 'plan', 'session', 'pack', 'best'];

export function isClientKind(v: string): v is ClientNotificationKind {
  return (KINDS as string[]).includes(v);
}

/**
 * §04's plate tones, and the one rule behind the mapping: **nothing here is
 * `danger`.** A client's feed is the surface a nervous beginner opens most, and
 * a red plate on a row whose only affordance is *go and look* is an alarm about
 * something that has already finished happening.
 *
 * Five kinds and five tones, each used once, which is not a coincidence — §04
 * has exactly five and the kinds were settled against them:
 *
 *   `note`    accent   the brand colour, on the one thing §"Make the trainer
 *                      present" calls the highest-value element in the product
 *   `plan`    floor    blue, the same plate the trainer's half gives the floor
 *   `session` diary    amber, the same plate it gives the diary
 *   `pack`    money    green, the same plate it gives money
 *   `best`    win      purple — the one modifier this half had to add, and
 *                      `app.css` carries why it is not called `team` here
 */
export const CLIENT_KIND_TONE: Record<ClientNotificationKind, string> = {
  note: 'reply',
  plan: 'floor',
  session: 'diary',
  pack: 'money',
  best: 'win',
};

/**
 * Where the row goes when it is opened.
 *
 * Every one lands on the screen that holds the FULL fact. None of the five is a
 * dead end, which is what makes this feed different from the trainer's — where
 * `hrefFor` returns `null` for a row with no client and the panel draws a fact
 * you cannot click. Every row here is about the person reading it, so every row
 * has somewhere to go.
 *
 *   `note`     `/me/account` — the Me tab, where *Notes from Arun* holds the
 *              history. Not Home: Home draws the NEWEST note and a row about
 *              one three days old would land on a screen showing a different
 *              one.
 *   `plan`     `/me/plan` — the schedule tab, which is what a client checks
 *              first after being told their plan moved.
 *   `session`  `/me/plan` too, and for the same reason: *Coming up* is the
 *              answer to "so when am I in".
 *   `pack`     `/me/account` — the pack card and its payment history.
 *   `best`     `/me/progress` — the summary, where the milestone chips are.
 */
export function clientHrefFor(kind: ClientNotificationKind): string {
  switch (kind) {
    case 'note':
    case 'pack':
      return '/me/account';
    case 'plan':
    case 'session':
      return '/me/plan';
    case 'best':
      return '/me/progress';
  }
}

/** The first line, split so the panel can bold the name and only the name. */
export interface ClientLine {
  /** Bolded. The trainer's first name on the four they did; null on `best`. */
  who: string | null;
  /** The rest of the sentence, starting lowercase where `who` leads. */
  said: string;
}

/**
 * The words. All of them, in one file, on purpose — the wire sends facts and
 * this is the only place that turns them into English, so a copy pass is a diff
 * here and nowhere else.
 *
 * ── THE TRAINER'S NAME LEADS ON FOUR OF THE FIVE ────────────────────────────
 *
 * The trainer's own feed bolds the CLIENT because that is what a trainer scans
 * a list of twenty-four people for. A client has one trainer, so the name is not
 * a disambiguator — it is the point. §"Make the trainer present" is the spec's
 * most repeated instruction and §"Notifications" turns it into a test: *"a
 * notification that reads as coming from a real person who knows them gets
 * opened; a generic nag gets the app deleted."* A row that opened *Your
 * programme was updated* is the generic nag, written by a product about itself.
 *
 * `best` is the one row the trainer did not do, so it does not claim they did.
 * It is written in the second person instead — *you hit a new best* — which is
 * the honest subject and the only row on this feed about the reader.
 */
export function clientLineFor(n: PortalNotificationWire, trainerFirst: string): ClientLine {
  switch (n.kind) {
    case 'note':
      return { who: trainerFirst, said: 'left you a note' };

    case 'plan':
      /* NEW or REWRITTEN, and the wire says which without a second kind:
         `subjectAt` is the block's own birthday, so a value equal to `at` is an
         assignment and anything earlier is an edit. It matters to the client —
         "wrote you a new plan" means everything changed, "changed your plan"
         means go and look at what did. */
      return {
        who: trainerFirst,
        said: n.subjectAt !== null && n.subjectAt < n.at ? 'changed your plan' : 'wrote you a new plan',
      };

    case 'session':
      switch (n.text) {
        case 'booked':
          return { who: trainerFirst, said: `booked you in for ${sessionWhen(n)}` };
        case 'moved':
          return { who: trainerFirst, said: `moved a session to ${sessionWhen(n)}` };
        default:
          /* *called off*, not *cancelled*. The word a trainer uses to a client
             about a session neither of them is going to make, and the softer of
             the two on the screen where the news lands. */
          return { who: trainerFirst, said: `called off ${sessionWhen(n)}` };
      }

    case 'pack':
      /* `rupees()` and not a template literal, which is the same call the pack
         card and the payment history make — so the three screens never print
         one amount three different ways, and the grouping is Indian. */
      switch (n.text) {
        case 'sold':
          return { who: trainerFirst, said: `started you on a new pack` };
        case 'renewed':
          return { who: trainerFirst, said: `renewed your pack` };
        default:
          return { who: trainerFirst, said: `recorded ${rupees(n.amount ?? 0)}` };
      }

    case 'best':
      return { who: null, said: 'You hit a new best' };
  }
}

/**
 * The second line, or null when the first has said everything.
 *
 * Null is the common case and that is deliberate. A feed where every row is two
 * lines is a feed of paragraphs; the detail is here for the rows where a second
 * fact changes what the client does about it — what the note actually said, what
 * the best actually was, which plan moved.
 */
export function clientDetailFor(n: PortalNotificationWire): string | null {
  switch (n.kind) {
    /* THE NOTE ITSELF, which is the row on this feed most likely to be read and
       never followed. §"Make the trainer present" is the reason it is worth the
       second line: a client who sees the first sentence of what their trainer
       wrote has already had the thing the notification is for, and the tap
       through to Me is for the rest. `mock/portal.ts` cuts it on a word. */
    case 'note':
    case 'best':
      return n.text;
    case 'plan':
      return n.text;
    case 'pack':
      /* Two different second lines, because `pack` is two different pieces of
         news wearing one plate.

         A SALE or a RENEWAL says what it cost. Neither prints the figure above,
         because *renewed your pack for ₹12,000* reads as an invoice arriving —
         and the amount still has to be somewhere a client can check against the
         card on Me, which is where the row lands.

         A PAYMENT already has the figure in its first line, so the detail is
         HOW it was recorded. That is the half a client is most likely to
         dispute: they paid by UPI on Tuesday and the book says cash. `method`
         is cased by `title()` for the reason `Account`'s payments table cases
         UPI by hand — a stylesheet `text-transform:capitalize` title-cases an
         acronym, and *Upi* is not a word. */
      if (n.text === 'sold' || n.text === 'renewed') {
        return n.amount === null ? null : rupees(n.amount);
      }
      return n.text ? `Recorded as ${title(n.text)}` : null;
    case 'session':
      return null;
  }
}

/** "Thursday's 07:00" — the session a row is about, inside the line. */
function sessionWhen(n: PortalNotificationWire): string {
  if (n.subjectAt === null) return 'a session';
  const d = new Date(n.subjectAt);
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  return `${WEEKDAYS[d.getDay()]}'s ${hh}:${mm}`;
}

const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

/** `upi` → `UPI`, `cash` → `Cash`. The wire sends the column's own value. */
function title(method: string): string {
  return method.length <= 3 ? method.toUpperCase() : method[0].toUpperCase() + method.slice(1);
}
