/**
 * A PDF, WRITTEN BY HAND, BECAUSE THE ALTERNATIVE IS A 300 kB DEPENDENCY.
 *
 * `package.json` carries four dependencies — `next`, `react`, `react-dom` and
 * `server-only` — and `card-image.ts` already refused html2canvas for that
 * reason and paints its own card instead. jsPDF is 350 kB minified and pdf-lib
 * is 1.4 MB; shipping either to every trainer so that one screen can produce
 * one attachment is the same bad trade one step further on.
 *
 * ── WHAT IS ACTUALLY NEEDED IS A VERY SMALL PART OF PDF ─────────────────────
 *
 * The pages of this report are PAINTED, exactly as the card is and for the same
 * three reasons: the layout must not inherit the trainer's window, the figures
 * must be identical to the ones on screen, and there must be one renderer to
 * keep right rather than two that drift. A painted page is an image, and a PDF
 * whose pages are images needs none of PDF's typography: no font programs, no
 * encodings, no text state, no widths tables. It needs a catalogue, a page
 * tree, and one image XObject per page.
 *
 * That is about ninety lines, and it is all of the format this file implements.
 * Anything that wants selectable text in the PDF wants a real library, and the
 * honest answer would be to add one rather than to grow this.
 *
 * ── THE IMAGES ARE JPEG AND GO IN UNTOUCHED — `/DCTDecode` ──────────────────
 *
 * PDF can carry a JPEG's own bytes as the stream of an image XObject, which is
 * the one filter a browser can produce for free: `canvas.toBlob(…, 'image/jpeg')`
 * emits exactly what `/DCTDecode` expects. So nothing here compresses, encodes
 * or transcodes anything — the bytes the canvas produced are the bytes in the
 * file, and a 3-page report is ~400 kB.
 *
 * PNG would need `/FlateDecode` with a `/Predictor`, which means unpacking the
 * browser's PNG and re-deflating it by hand. JPEG at 0.92 on a page that is
 * flat fills and text at 150 dpi is indistinguishable, and this is the one
 * artefact of the three whose job is to be read rather than to be posted.
 *
 * ── AND IT IS BYTES, NOT A STRING ───────────────────────────────────────────
 *
 * The xref table records a BYTE offset for every object, so the whole file is
 * assembled as `Uint8Array` chunks with a running count. Built as a string it
 * would be correct until the first client whose name has a `ñ` in it: `TextEncoder`
 * emits two bytes for that character and `String.length` counts one, so every
 * offset after the title would be short by one and the file would not open.
 * Nothing in the report's own content reaches the PDF's syntax — but the
 * `/Title` does, and that is a client's name.
 */

/** A4 at 72 dpi, which is PDF's unit. 210 × 297 mm. */
export const A4_PT = { w: 595.276, h: 841.89 } as const;

/** A4 at 150 dpi — what the pages are painted at. The ratio matches `A4_PT`
 *  to within a third of a pixel, so a page fills its sheet with no letterbox. */
export const A4_PX = { w: 1240, h: 1754 } as const;

export interface PdfImagePage {
  /** The JPEG's own bytes, straight from `canvas.toBlob`. */
  jpeg: Uint8Array;
  /** The pixel dimensions of that JPEG. */
  w: number;
  h: number;
}

const enc = new TextEncoder();

/**
 * A PDF TEXT STRING, AND IT HAS TO BE UTF-16 — MEASURED IN A GENERATED FILE.
 *
 * The first version was a literal: escape `\`, `(` and `)` and wrap the rest in
 * brackets. That is correct PDF for ASCII and silently wrong for everything
 * else, because a bracketed literal with no byte-order mark is read as
 * **PDFDocEncoding** — a single-byte encoding. So the UTF-8 bytes of an em dash
 * went in as three characters and the file's `/Title` came back
 * `Nithya Iyer â€” progress report`, which is what a reader shows in its tab and
 * what a mail client shows as the attachment's name.
 *
 * It was found by reading the generated bytes back, and it would have been
 * invisible on a test in English with a hyphen. The report's own title carries
 * an em dash on every client, and the CLIENT'S NAME is in it — which on this
 * product is as likely to be in Tamil or Devanagari as in Latin script.
 *
 * So: UTF-16BE with the `þÿ` mark, written as a hex string. Hex rather than a
 * literal because UTF-16 of ASCII is full of NUL bytes, and a literal would
 * then need `\000` escapes throughout — more escaping, not less. Nothing inside
 * a hex string is special, so the bracket case the old note worried about
 * cannot arise at all.
 *
 * `charCodeAt` and deliberately NOT `codePointAt`: a JavaScript string is
 * already UTF-16, so its code UNITS are exactly the code units UTF-16BE wants —
 * an astral character arrives as its surrogate pair and is written straight
 * through. `codePointAt` would decode that pair into one value above 0xFFFF
 * and `padStart(4)` would then emit five hex digits, desynchronising every
 * character after it. An emoji in a client's name survives this way and not
 * the other.
 */
function pdfString(s: string): string {
  let hex = 'FEFF';
  for (let i = 0; i < s.length; i += 1) {
    hex += s.charCodeAt(i).toString(16).toUpperCase().padStart(4, '0');
  }
  return `<${hex}>`;
}

/**
 * The pages, in order, as one PDF blob.
 *
 * Object numbering is fixed and not incidental: 1 is the catalogue, 2 the page
 * tree, 3 the document information, and then each page takes three consecutive
 * objects — the page, its content stream, its image. So page `i`'s page object
 * is `4 + i * 3`, which is what `/Kids` is built from and what lets the xref be
 * written in one pass.
 */
export function imagePagesToPdf(
  pages: PdfImagePage[],
  meta: { title: string; author: string; subject?: string },
): Blob {
  const chunks: Uint8Array[] = [];
  let length = 0;
  const push = (part: Uint8Array | string) => {
    const bytes = typeof part === 'string' ? enc.encode(part) : part;
    chunks.push(bytes);
    length += bytes.length;
  };

  /* Object number → byte offset. Index 0 is the free object PDF requires. */
  const offsets: number[] = [0];
  const obj = (n: number, body: string) => {
    offsets[n] = length;
    push(`${n} 0 obj\n${body}\nendobj\n`);
  };

  push('%PDF-1.4\n');
  /* Four bytes above 127, which is the convention that tells a transport this
     is binary and must not be newline-translated. Sent through anything that
     "helpfully" converts CRLF, a PDF without this marker arrives corrupt. */
  push(new Uint8Array([0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a]));

  const pageNo = (i: number) => 4 + i * 3;
  const kids = pages.map((_, i) => `${pageNo(i)} 0 R`).join(' ');

  obj(1, '<< /Type /Catalog /Pages 2 0 R >>');
  obj(2, `<< /Type /Pages /Count ${pages.length} /Kids [ ${kids} ] >>`);
  obj(
    3,
    `<< /Title ${pdfString(meta.title)} /Author ${pdfString(meta.author)}` +
      `${meta.subject ? ` /Subject ${pdfString(meta.subject)}` : ''}` +
      ` /Producer (InclineYou) /Creator (InclineYou) >>`,
  );

  pages.forEach((page, i) => {
    const pageObj = pageNo(i);
    const contentObj = pageObj + 1;
    const imageObj = pageObj + 2;

    /* The image is scaled to FILL the sheet, and `A4_PX` is chosen so that the
       scale is 1:1 on both axes. A page painted at some other size still
       works — it is stretched to the sheet, which for a page of this report's
       own painting is what "fits the paper" means. */
    const content = `q\n${A4_PT.w.toFixed(3)} 0 0 ${A4_PT.h.toFixed(3)} 0 0 cm\n/Im0 Do\nQ\n`;

    obj(
      pageObj,
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${A4_PT.w.toFixed(3)} ${A4_PT.h.toFixed(3)}]` +
        ` /Resources << /XObject << /Im0 ${imageObj} 0 R >> >>` +
        ` /Contents ${contentObj} 0 R >>`,
    );

    obj(contentObj, `<< /Length ${content.length} >>\nstream\n${content}endstream`);

    /* The image XObject. `/DCTDecode` and the JPEG's bytes verbatim — see the
       file note. `/DeviceRGB` with `/BitsPerComponent 8` is what a canvas
       emits; it never produces a greyscale or CMYK JPEG. */
    offsets[imageObj] = length;
    push(
      `${imageObj} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${page.w} /Height ${page.h}` +
        ` /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode` +
        ` /Length ${page.jpeg.length} >>\nstream\n`,
    );
    push(page.jpeg);
    push('\nendstream\nendobj\n');
  });

  const xrefAt = length;
  const count = offsets.length;
  /* Every entry is exactly 20 bytes — `nnnnnnnnnn ggggg n\r\n` — and a reader
     that seeks by arithmetic will land in the middle of the next one if any
     entry is short. Hence the padding rather than a template string. */
  let xref = `xref\n0 ${count}\n0000000000 65535 f \n`;
  for (let n = 1; n < count; n += 1) {
    xref += `${String(offsets[n] ?? 0).padStart(10, '0')} 00000 n \n`;
  }
  push(xref);
  push(`trailer\n<< /Size ${count} /Root 1 0 R /Info 3 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`);

  return new Blob(chunks as BlobPart[], { type: 'application/pdf' });
}

/** A canvas as the JPEG bytes a page wants. Null where `toBlob` refuses, so a
 *  caller can fall back to the image share rather than throw on a button. */
export async function canvasToJpeg(canvas: HTMLCanvasElement): Promise<PdfImagePage | null> {
  const blob = await new Promise<Blob | null>((resolve) => {
    try {
      canvas.toBlob((b) => resolve(b), 'image/jpeg', 0.92);
    } catch {
      resolve(null);
    }
  });
  if (!blob) return null;
  return {
    jpeg: new Uint8Array(await blob.arrayBuffer()),
    w: canvas.width,
    h: canvas.height,
  };
}
