-- THE ACCOUNT — the section of Settings that is not about coaching at all.
--
-- V33, V34 and V35 added columns a CLIENT reads: a headline, a bio, a place, a
-- set of links. This adds the one column the trainer reads about themselves,
-- and it sits beside the two that were already there and had never been shown:
-- `phone`, which is the login, and `name`, which every other screen greets them
-- by.
--
-- ── ONE COLUMN, AND IT IS DELIBERATELY NOT A SECOND LOGIN ───────────────────
--
-- There is no email anywhere in this product and there was none before today.
-- Sign-in is a phone number and a six-digit code (`otp_request`, `app_user`),
-- there is no mail transport configured, no verification token table and no
-- template. **`email` is therefore a CONTACT DETAIL and not a credential**, in
-- the same position V33's bio is in: stored, shown back, and branched on by
-- nothing.
--
-- That is worth stating in the schema rather than discovering later, because
-- the obvious next feature — "sign in with your email" — is not one column
-- away. It needs a verification round trip this backend has no way to send, and
-- until it can, an unverified string is exactly as much as we are entitled to
-- claim. So:
--
--   * NOT UNIQUE. Two trainers sharing a studio inbox is not an error, and a
--     unique index would turn a typo into somebody else's account being
--     unreachable. Uniqueness is a property of a login, and this is not one.
--   * NOT NOT-NULL. Every trainer who exists today has no email and is not
--     broken; NULL means never answered, as it does in V33, V34 and V35.
--   * NO INDEX. Nothing queries by it. An index would be the first quiet
--     suggestion that something does.
--
-- 254 is the RFC 5321 ceiling on an address (64 local + @ + 253 domain, capped
-- at 254 by the path length). Refused over the cap rather than truncated, like
-- `headline` and `bio` and for their reason: half an address is not a shorter
-- address, it is a wrong one.
--
-- ── WHAT THIS MIGRATION DOES NOT ADD, AND WHY ───────────────────────────────
--
-- **Nothing for changing a phone number.** `POST /v1/trainers/me/phone/*`
-- rewrites `trainer.phone` and `app_user.phone` in one transaction and proves
-- possession of both numbers with the OTP machinery that already exists — two
-- codes, two `otp_request` keys, no new state. The "you proved the old number"
-- step is carried by a short-lived signed ticket rather than a row, because a
-- table would be a second place for a half-finished change to live and a
-- ten-minute JWT expires without anybody having to sweep it.
--
-- **Nothing for deleting an account.** `deleted_at` has been on `trainer` since
-- V1 and on `app_user` since V18, and `DELETE /v1/trainers/me` stamps both.
-- There is no hard delete and there cannot be a cheap one: `trainer.id` is a
-- NOT NULL foreign key from `client`, and twenty tables hang off that in turn.
--
-- The consequence is stated here because it is a promise the product makes to
-- somebody on their way out: **a deleted account's phone number is not
-- released.** `trainer.phone` and `app_user.phone` are both plain UNIQUE
-- indexes, not partial on `deleted_at`, so the row keeps the number and a fresh
-- sign-up on it is refused. Making them partial would free the number and is a
-- deliberate non-goal: the trainer's clients, packages, payments and session
-- history all still point at that row, and handing the number to a second
-- person would put a stranger's sign-in next to a year of somebody else's
-- money. The confirm step says so in as many words before the button works.
--
-- Additive only: one nullable column on an existing table.

ALTER TABLE trainer
    -- A contact address. NOT a login — see above. NULL means never answered.
    ADD COLUMN IF NOT EXISTS email VARCHAR(254);
